default:
  golem_name: shinycal
  golem_version: 0.4
  app_prod: no
  cal_host: "nextcloud.r-podcastdev.link"
  cal_base_url: "https://nextcloud.r-podcastdev.link/remote.php/dav/calendars/shinycal"
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
